{% set version = '0.5' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-registry
  version: {{ version|replace("-", "_") }}

source:
  fn: registry_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/registry_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/registry/registry_{{ version }}.tar.gz
  sha256: 5d8be59ba791987b2400e9e8eaaac614cd544c1aece785ec4782ea6d5ea00efb


  # patches:
   # List any patch files here
   # - fix.patch

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  noarch: generic

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  build:

  host:
    - r-base

  run:
    - r-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('registry')"           # [not win]
    - "\"%R%\" -e \"library('registry')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=registry
  license: GPL-2
  summary: Provides a generic infrastructure for creating and using registries.
  license_family: GPL2

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: registry
# Type: Package
# Title: Infrastructure for R Package Registries
# Version: 0.5
# Author: David Meyer
# Maintainer: David Meyer <David.Meyer@R-project.org>
# Description: Provides a generic infrastructure for creating and using registries.
# Depends: R (>= 2.6.0)
# Imports: utils
# License: GPL-2
# NeedsCompilation: no
# Packaged: 2017-12-02 16:29:01 UTC; meyer
# Repository: CRAN
# Date/Publication: 2017-12-03 09:35:10 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
