# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R=3.3.2
    - CONDA_R=3.4.1
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Zh749FmetagwANE/QQmA9hABYpbCZ2u67+Z4AdnEHsUZvRA2/2oR3T+FiFv2cykfriRUfcRWHIH6+oHDfN54MXoIjMFvLwDcEGxkWI25nQtzpTQ26sx+VmkeVON90Wkdvw8mf2yZkCFP0rSNJvxyFu9yB065MbgvrRQbDRT2jnEU726U5rWVNZtV6B2bblwuykg+peuHeZzSO/VJv32+eT7xL92dx+t/oUq/ry9dDQPowItttg6tJnpB1mIx8l0vxIZB1lNDXgJqddS+YTh8LlxiPJP2+zmRwzHwOmOrsnhxTbEwVeJ9Yzmchd7zYj3xlOMCSqqjvgdLkaibix/GzdJcIe4qK1OVW1opIvfBM1zUao96Ams1rOfPajKLJhGGIQSo7jxDv7ugRBXBjTervtH+FxGRlSAa64S1X3j0MILvxO6/n/4Mc3L9uVoc8p/PbgkOkJy3CY+8cDS1k/Yqrjr6Yik+lr0WSN43PL1/35ISJF8ps9vzkOovO2Dg0ceDq0DgFr8XLLI13Z+1yxPs/ZSKGa0MO5CCTaf4XQrwXCoMh6/Yvscj2vv0C28qvaBdsKVIddJ2B/Hb3DUMw8a4PtgvNNjI03HLAPnXe6lxA2Nq5karGQyc5C+bv6rLMp/5gfikbezdW9V4RenOp3Sys4gnp3EXNUp5uof4hp2p9/k="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
