travis:
  secure:
    BINSTAR_TOKEN: Zh749FmetagwANE/QQmA9hABYpbCZ2u67+Z4AdnEHsUZvRA2/2oR3T+FiFv2cykfriRUfcRWHIH6+oHDfN54MXoIjMFvLwDcEGxkWI25nQtzpTQ26sx+VmkeVON90Wkdvw8mf2yZkCFP0rSNJvxyFu9yB065MbgvrRQbDRT2jnEU726U5rWVNZtV6B2bblwuykg+peuHeZzSO/VJv32+eT7xL92dx+t/oUq/ry9dDQPowItttg6tJnpB1mIx8l0vxIZB1lNDXgJqddS+YTh8LlxiPJP2+zmRwzHwOmOrsnhxTbEwVeJ9Yzmchd7zYj3xlOMCSqqjvgdLkaibix/GzdJcIe4qK1OVW1opIvfBM1zUao96Ams1rOfPajKLJhGGIQSo7jxDv7ugRBXBjTervtH+FxGRlSAa64S1X3j0MILvxO6/n/4Mc3L9uVoc8p/PbgkOkJy3CY+8cDS1k/Yqrjr6Yik+lr0WSN43PL1/35ISJF8ps9vzkOovO2Dg0ceDq0DgFr8XLLI13Z+1yxPs/ZSKGa0MO5CCTaf4XQrwXCoMh6/Yvscj2vv0C28qvaBdsKVIddJ2B/Hb3DUMw8a4PtgvNNjI03HLAPnXe6lxA2Nq5karGQyc5C+bv6rLMp/5gfikbezdW9V4RenOp3Sys4gnp3EXNUp5uof4hp2p9/k=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
