travis:
  secure:
    BINSTAR_TOKEN: Pv28BKvqWuECuh1eHRsULflSddYl+q4l3sjMhAFmBdbRwI03pTf16xAdeuXaKYTa0AgPgxSGNLUcDldDqnXkS+5StPsY20XmCRAWvm19Ym0TkI3wj0Zh+fRaZszq+DRAQ0i9GSBnjW6VQVRigmzd9C47bMdJLyLhCtGIqDqETnduRLlfOa8Cf3FCAxppzdI23gGu9J297ERBQ6zy8vSigrWcJ131ANlOd1m1lpBUGn67FkxC41iLp7DdvOP8/Gn0XH/bjaTJIfGiDF6C11fffNF31sIjbzLEzq+Hux7e3Vu3lerHONLmV+eGJgma696OcwDCdWx2NBgJs/uVYluNG+svhRgBlpJUnyU3nnl8gnE7KoPSDHhvlRkD9prEHLP2FQO4xAwniNTeVvtMcXCxLLC3VVWDDEPOsE3Cmx9AQAZoeIshKsB2UEohpAFc7wTEC7p6NiX7OleiZiv45jEDaFU2+sk94yzJDz4JiIFKnTjicc50mA3gE2gVVPPeN5LjQr9NsfRwQy7JDIxv/vkhrmexNx0WPPNPa4OVMnLqmt21ouc9DVUvsGHjuCES88zta8IjnUgw2k9N5R+0h8a0esxsa0UAqebdA26pl18a1pVxsFp1KJH/y9n8b6Qcl05OgR22po3jDYIUwBXAWSTHoxsiA4mHJv7PHxJa/ktzVhQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
