travis:
  secure:
    BINSTAR_TOKEN: oGNRxQeEsW+JNFLg6pIqpZ8wUouBz2FdmKK3dMQp7mdfCUCHS+nEVb1WCVeYqJlBqm7swl+3Mqw2l3owCnFT00HHw45sWQEwZgp82cGtP3ckb89s5egFA0WvHAWcefsnEzRJ/6f1bHoS8HHw9MGjM/JeJ5kuJjEdRlb3IsO3K3SXA0BXE1ZC1GR9JlHZhfeBdsiDjf94RJBr0HOMB3tMkaf8HVYXJY/CP/7JIXSuAU1ym5QEF4w1X0aeuH2iGwhw2G71uTH0OdUpSEws9z8FCOTc8gOT6yodQ1BFt3zOGHYJV/miM6gDs7T4sCrUcTM1En3qsot0/qDWo7OKKsEcVuGiEkLhrafs/FChFe7fYECxT2ZZNmzj5YecEThiJ/HcAZggXWws8FLwbgObSQJ6Q4OCfkAjElYPWCnwlUpXVnJxeSgmq2Tdsy9qRfaz/QWyaRQkfHodvzldZLSW32tJzP8xEUpVz/7H+CsiufVqk4PLVPhfm7dlBu4KBtcdBbeTMaTiakP3JcLoXI86zHAhST4/XW21bLazN6ADs67dKkX6vkaIOKSKg5PBjPfFycUPLMHfk3WmWZiQvdro4fILL301Z9GDOMyVmxf1ZnWtr+YuaCkdaHegrIdYzAzmeNyLa74fwHWoKbKKEe4jFqnIvCAgaLkkFtl1+Jb9qLQZazE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
